### ISSUE TITLE
Firmware source code?

### ISSUE THREAD

**Issue by alexvnesta** [smartgauges/usb2most#4]
Hello, 

I am interested in interfacing with the MOST OS81050 chip in my BMW radio.

I want to provide the chip with an I2S signal and have that audio signal be sent to the car amplifier.

Would you please upload any code/information you have involving the OS81050 chip that may be useful for me?

Thank you,
Alex

**Comment by smartgauges** [comment]
Hello,

I couldn't find public documentation for the OS81050 chip
I this project i use os8104a chip.
