### ISSUE TITLE
Resources for most

### ISSUE THREAD

**Issue by rhysmorgan134** [smartgauges/usb2most#5]
Hi,

I love your work you have done some really interesting stuff and written some really interesting documentation! One part i am wondering, how did you figure all of this out with the MOST bus? Information on it seems very well hidden out side of car manufacturers. I am working one a replacement touch screen for my jaguar, but the real tricky part is that it seems the old screen will have to be present for MOST bus control somwhere!

Thanks again! I've spent many hours reading your posts online

**Comment by smartgauges** [comment]
Hello, thanks and sorry for the late reply.
In general terms, the specification for the MOST bus is open and can be found at [mostcooperation.com](https://www.mostcooperation.com/specifications/), also there you can find some specifications for different types of equipment (amplifier, HU, radio...) 
[MOST_2V5_FBlock_Library](https://www.mostcooperation.com/fileadmin/content_filestorage/specifications/MOST_version_2V5/MOST_2V5_FBlock_Library.zip)
But almost always the vendor makes some vendor-specific features ((
What model is your jaguar?

**Comment by rhysmorgan134** [comment]
Thankyou! I will take a good long read of that.

My jaguar is a 2008 XF, these contain the canbus-most gateway under the CD player. Currently I have relocated the screen and am making use of proxy device to overwrite the canbus messages from this for my needs.

However I would love to replace this entirely. I am awaiting some OS8104 chips to come and maybe have a play, being able to create a MOST sniffer similar to what we use for CAN would be the first goal! 

As an aside, I also have a 2007 Freelander 2 which is next in my list to have a play with, so your resources will be hugely useful for that too!

**Comment by rhysmorgan134** [comment]
Me again, I have been having a play with an os8104 chip and have managed to communicate with it and configure it. However when I put it in the MOST loop it seems to be creating some errors as the most loop keeps turning on and off my transceiver does power up and I have currently set it to all bypass.

would there be any chance of you sharing your start up registers and the values you are writing? I am also running and 18.432 MHz crystal, and looking through the manual this seems to point to the most frequency being 48Hz, so currently unsure as to why it seems to be faulting out the loop.

huge thanks again for what you shared on here, helped hugely in my experimentations so far!

**Comment by rhysmorgan134** [comment]
Never mind, got the PCB and all works on there well, so issue must have be RX and TX legs being too long!

![346E4AF7-0FC1-458B-B843-FBB492B2383C](https://user-images.githubusercontent.com/36861722/226481273-bc90a2ee-dd69-4479-adb3-6650823364ea.jpg)
